### ISSUE TITLE
warning message - 0% accuracy

### ISSUE THREAD

**Issue by tuc289** [BMBGenomics/BtToxin_Digger#16]
I am getting messages while running the program as 

"Accuracy = 0% (0/12512) (classification)" 

This message came out even when I was running 'tests' data to check the installation. I checked the results from the test dataset, and it was identical to Result_Files 

Do you have any ideas of what that means and how that affects my results? 

Please refer to the code I used below (I have ~100 genome contigs in the same directory named as *_unicycler.fasta)--

BtToxin_Digger --threads 8 --SeqPath ./ --SequenceType nucl --Scaf_suffix _unicycler.fasta 

Thanks!

**Comment by liaochenlanruo** [comment]
@tuc289 Hi, the massage does not mean any error and does not affect the accuracy of the result, just ignore that!

**Comment by tuc289** [comment]
Thanks for the confirmation!
